# Generated by Django 4.0.10 on 2024-04-01 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authoringtool', '0004_alter_activitytype_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='plain_text',
            field=models.TextField(blank=True),
        ),
    ]
