# Generated by Django 4.0.10 on 2024-04-02 12:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authoringtool', '0006_answer_answerfeedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='created_by',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='created_answers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='answer',
            name='updated_by',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='updated_answers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='answerfeedback',
            name='created_by',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='created_answer_feedbacks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='answerfeedback',
            name='updated_by',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='updated_answer_feedbacks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='NextQuestionLogic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='next_logic', to='authoringtool.activity')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='next_logic', to='authoringtool.answer')),
                ('next_activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='previous_logic', to='authoringtool.activity')),
            ],
            options={
                'verbose_name': 'Next Question',
                'verbose_name_plural': 'Next Questions',
                'ordering': ['activity'],
                'unique_together': {('activity', 'answer')},
            },
        ),
    ]
