# Generated by Django 4.0.10 on 2024-04-02 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authoringtool', '0007_alter_answer_created_by_alter_answer_updated_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nextquestionlogic',
            name='answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next_logic', to='authoringtool.answer'),
        ),
    ]
