# Generated by Django 4.0.10 on 2024-04-02 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authoringtool', '0008_alter_nextquestionlogic_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='name',
            field=models.CharField(default='ActivityDefaultName', max_length=255),
        ),
    ]
