# Generated by Django 4.0.10 on 2024-04-03 10:11

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authoringtool', '0009_activity_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvQuestionBranching',
            fields=[
                ('activity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='branching', serialize=False, to='authoringtool.activity')),
                ('next_question_on_high_feedback', models.TextField(blank=True)),
                ('next_question_on_mid_feedback', models.TextField(blank=True)),
                ('next_question_on_low_feedback', models.TextField(blank=True)),
                ('next_question_on_high', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_high', to='authoringtool.activity')),
                ('next_question_on_low', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_low', to='authoringtool.activity')),
                ('next_question_on_mid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_mid', to='authoringtool.activity')),
            ],
            options={
                'verbose_name': 'Evaluating Question Branching',
                'verbose_name_plural': 'Evaluating Question Branching',
                'ordering': ['activity'],
            },
        ),
        migrations.CreateModel(
            name='ActivityBunch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_ids', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('activity_primary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_bunches', to='authoringtool.activity')),
            ],
            options={
                'verbose_name': 'Activity Bunch',
                'verbose_name_plural': 'Activity Bunches',
                'ordering': ['activity_ids'],
            },
        ),
    ]
