# Generated by Django 4.0.10 on 2024-04-03 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authoringtool', '0010_evquestionbranching_activitybunch'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ActivityBunch',
            new_name='QuestionBunch',
        ),
    ]
