# Generated by Django 4.0.10 on 2024-04-25 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authoringtool', '0012_alter_nextquestionlogic_next_activity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Simulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('iframe_url', models.URLField()),
                ('width', models.PositiveIntegerField(default=800)),
                ('height', models.PositiveIntegerField(default=600)),
                ('allow_fullscreen', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Simulation',
                'verbose_name_plural': 'Simulations',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='activity',
            name='simulation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authoringtool.simulation'),
        ),
    ]
