# Generated by Django 4.0.10 on 2024-04-26 14:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authoringtool', '0013_simulation_activity_simulation'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserScenarioScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_score', models.IntegerField(default=0)),
                ('timeDoingScenario', models.IntegerField(blank=True, default=0, null=True)),
                ('last_activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authoringtool.activity')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authoringtool.scenario')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User & Scenario Score',
                'verbose_name_plural': 'User & Scenario Scores',
                'ordering': ['user'],
            },
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timing', models.DurationField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authoringtool.activity')),
                ('answer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authoringtool.answer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "User's Answer",
                'verbose_name_plural': "User's Answers",
                'ordering': ['user'],
            },
        ),
    ]
