# Generated by Django 4.0.10 on 2024-04-27 18:14

from django.db import migrations, models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authoringtool', '0014_userscenarioscore_useranswer'),
    ]

    operations = [
        migrations.CreateModel(
                    name='UserAnswer',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('timing', models.IntegerField(blank=True, null=True)),
                        ('created_on', models.DateTimeField(auto_now_add=True)),
                        ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authoringtool.activity')),
                        ('answer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authoringtool.answer')),
                        ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                    ],
                    options={
                        'verbose_name': "User's Answer",
                        'verbose_name_plural': "User's Answers",
                        'ordering': ['user'],
                    },
                ),
    ]
