# Generated by Django 4.0.10 on 2024-04-27 18:44

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authoringtool', '0018_useransweringnow_delete_useranswer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserAnsweringnow',
            new_name='UserAnswer',
        ),
    ]
