# Generated by Django 4.0.10 on 2024-05-09 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authoringtool', '0019_rename_useransweringnow_useranswer'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'School Department',
                'verbose_name_plural': 'School Departments',
                'ordering': ['id'],
            },
        ),
    ]
