# Generated by Django 4.0.10 on 2024-06-12 11:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authoringtool', '0020_schooldepartment'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhetLabSessions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Phet Default', max_length=255)),
                ('mass_1', models.FloatField(blank=True, null=True)),
                ('mass_2', models.FloatField(blank=True, null=True)),
                ('length_1', models.FloatField(blank=True, null=True)),
                ('length_2', models.FloatField(blank=True, null=True)),
                ('angle_1', models.FloatField(blank=True, null=True)),
                ('angle_2', models.FloatField(blank=True, null=True)),
                ('gravity', models.FloatField()),
                ('friction', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='authoringtool.activity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Phet Lab Session',
                'verbose_name_plural': 'Phet Lab Sessions',
                'ordering': ['user'],
            },
        ),
    ]
