# Generated by Django 4.0.10 on 2024-07-11 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authoringtool', '0021_phetlabsessions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='score_limit',
            field=models.FloatField(default=0.0),
        ),
    ]
