# Generated by Django 4.0.10 on 2024-10-30 13:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authoringtool', '0024_experimentll_activity_experiment_ll'),
    ]

    operations = [
        migrations.CreateModel(
            name='RemoteLabSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('lab_name', models.CharField(max_length=255)),
                ('pre_duration', models.DurationField()),
                ('exec_duration', models.DurationField()),
                ('mass', models.CharField(max_length=255)),
                ('angle', models.IntegerField()),
                ('iteration', models.IntegerField()),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_sessions', to='authoringtool.activity')),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_sessions', to='authoringtool.phase')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_sessions', to='authoringtool.scenario')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'LabsLand Lab Session',
                'verbose_name_plural': 'LabsLand Lab Sessions',
                'ordering': ['id'],
            },
        ),
    ]
