# Generated by Django 4.0.10 on 2025-04-12 13:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authoringtool', '0025_remotelabsession'),
    ]

    operations = [
        migrations.CreateModel(
            name='VRARExperiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('launch_url', models.URLField()),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr_codes/')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='vr_ar_experiment_pictures/')),
            ],
            options={
                'verbose_name': 'VR/AR Experiment',
                'verbose_name_plural': 'VR/AR Experiments',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='MultilingualQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text_en', models.TextField(verbose_name='Question (English)')),
                ('question_text_pt', models.TextField(blank=True, verbose_name='Question (Portuguese)')),
                ('question_text_gr', models.TextField(blank=True, verbose_name='Question (Greek)')),
                ('question_text_es', models.TextField(blank=True, verbose_name='Question (Spanish)')),
                ('question_text_fr', models.TextField(blank=True, verbose_name='Question (French)')),
                ('question_text_de', models.TextField(blank=True, verbose_name='Question (German)')),
                ('is_required', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='created_multilingual_questions', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='updated_multilingual_questions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Multilingual Question',
                'verbose_name_plural': 'Multilingual Questions',
                'ordering': ['order', 'created_on'],
            },
        ),
        migrations.AddField(
            model_name='activity',
            name='vr_ar_experiment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authoringtool.vrarexperiment'),
        ),
        migrations.CreateModel(
            name='MultilingualAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='created_multilingual_answers', to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='authoringtool.multilingualquestion')),
                ('scenario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question_answers', to='authoringtool.scenario')),
                ('updated_by', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='updated_multilingual_answers', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Multilingual Answer',
                'verbose_name_plural': 'Multilingual Answers',
                'ordering': ['-created_on'],
                'unique_together': {('question', 'user', 'scenario')},
            },
        ),
    ]
